use rand::{rng, Rng};

pub fn motd() -> String {
    let motd_vec = ["100% lag free", "100% organic", "144p GAMEPLAY!", "1 BEST DATING SERVER", "1 was the original number", "2b2t and smoke weed", "2b2t> home of the largest CP pixel art collection", "2b2t is full", "2b2t is full ya know", "2b2t is Narnia", "2B2T.ORG IS THE BEST MINECRAFT SERVER", "2b2t peaceful smp happy people on!", "2b2t woop woop", "2bombs2terrorists", "2builders2terrorists", "2twin2towers", "666 Kill Hitler 666",
        "666! The number of the beast!", "9mm with my homies", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", "A blackhole of destruction into", "Accept it.", "actualy, yes i did have a bite", "Alea iacta est.", "A little fruity", "All aboard the vetrain", "All aboard the Vetrain!", "All praise the Melon Goddess!", "All servers are located in a hut in cuba", "All that you know will fade...", "All your friends are online!", "already a map of north korea", "also i'd just like to thank you for", "also, i like to make the sex with the doritos",
        "a mountain of rubble and death", "an everlasting war between order and chaos", "An exploit was disabled due to", "An uncontained SCP.", "Any cute girls on today :3", "Anyone wanna grief the Valley of Wheat?", "A oeaceful christian server", "Ask about the cactus dupe!", "As seen on /b/!", "As seen on /co/", "as seen on TV!", "'Autism' has more than 300 definitions here", "Autistic screeching ahead", "backdoor'd", "BEHOLD.", "Best christian factions server.", "BIGGEST BATTLE IN 2B2T HISTORY!!", "BIGGEST GRIEF IN 2B2T HISTORY!!", "BIGGEST VILLAGE IN MINECRAFT!!",
        "Birds are disabled due to an exploit", "BIRD UP!", "Bite my shiny metal ass", "blaze it faggot", "Blocks are disabled due to an exploit", "Break a block, then break it again!", "Burn it, burn it all!", "Burst some Pepsi out!", "But there's already one that is just like this?", "buy more coke right now", "Cactus dupe is best dupe.", "Can't connect to server.", "Certified Mojang Testing Grounds.", "Chill, it's just a block game.", "christian mlp anarchy server", "Clown down!", "Cogito, ergo sum.", "coke > pepsi", "Coming Soon, 2b2tCon!", "COMMUNICATION ERROR", "consider yourself sacrificed",
        "co-ordinates are currency", "Crafting is disabled due to an exploit", "!!! CRINGE WARNING !!!", "cringey", "Crystal PvP is the only PvP", "Daily reminder that AgentGB won the war", "Daily reminder to brush your teeth.", "dark souls of minecraft", "dead forever", "dead geam", "Dead server, don't join", "Death ahead", "Death is only a temporary inconvenience.", "DEDICATION MOTIVATION ACCELERATION", "DEEP FREEZE DEEP FREEZE DEEP FREEZE", "[deleted]", "delete this", "DELETE THIS", "Delet This!", "Deplorables Anonymous", "Destroy Build Destroy: Minecraft edition", "Did you know?", "Did you know? No, you didn't!",
        "Did you know? No you didn't!", "Disiecta membra poetae.", "Does anybody have food?", "do /kill veteran to join #team veteran", "dont ask questions", "Don't dig straight down!", "Don't eat yellow snow!", "Dont even start, turn around", "dont join this is virused", "Don't look behind you.", "Do you have a moment to talk about our", "Do you is fucking?", "Drink Pepsi everyday!", "Dupe your cactus with the cactus dupe!", "eat a shit FAGOT", "edgy sentence here", "Egg!", "Either. Or Both. Depends on perspective.", "Elitist regulars inside!", "end of the line", "Enjoy!", "even the border is griefed", "Ever had a fresh bite of WINTERMELON?",
        "Every day is the same!", "Everyone is a shit", "Everyone on 2b2t is a bot except you", "Every Time Lightning strikes, a veterean dies", "Exploits are temporarily disabled", "Family Friendly Christian server!", "feel free to build 10k out", "Fishing is temporarily disabled", "Fit did nothing wrong", "Fit good, but rush", "fitsgoodbutrush", "FIVE YEARS", "Fix the damn end portals", "FIX THE LADDERS", "Format your hard drive today!", "FOUR YEARS", "Free diamonds for youtubers", "Free Door Giveaway!", "friendly players on", "fucc", "fun fact this server is played by mimes", "Game time started", "Get on the bus, leave it all to us", "Get out of my chair!",
        "GET UP ON THE HYDRA'S BACK", "git gud", "GIT GUD", "give the suc", "goates", "Go away, we're full.", "GOD WILL NOT SAVE YOU HERE", "Good luck.", "HACKEDBYTEAMRUSHER!", "Happiness only real when shared", "Happy birthday to my wife", "Happy senior man approves this message!", "has voted", "HATEHATEHATEHATEHATEHATEHATEHATE", "have you ever seen a", "Heavily Moderated", "Hell is empty and all the devils are here.", "Here's your daily dose of autism.", "he said max of three you fucling sperg", "HE WILL NOT DIVIDE US", "HEY GUYS AND WELCOME BACK TO ANOTHER...", "Hey kid, wanna join #TeamVetrain?", "HEY LOOK GUYS I FIGURED OUT", "hggh ygh yg", "history.3gp",
        "Home is where the deception happens", "Home of the Vetain and rasher war", "Hookers and Blow!", "hopefully you posted this ironically", "Horse+Forest=RageQuit", "Hotdogs, hamburgers, hookers and blow", "how do i dupe donkies", "how do i get food", "How do i green text?", "How its cqlled when you reach a black hole?", "how to escape spawn!!! help pls!!!", "i am not gay i promise", "I am the church", "I could kill you all in 3 seconds.", "i dont come here for the game", "I fucking love eggplants", "If you are thinking about joining call this number", "/ignore is your only friend here.", "I hate God because my crush didn't like me", "I hope not but oh well",
        "I just mined 14 Dirt!", "I just mined 1 TNT!", "I just mined one bedrock!", "I just picked up 64 Netherrack!", "I knew you would be back!", "I laugh to hide the pain", "i log on about 6 times a day", "I look around, I look around,", "I'm just wandering around my base aimlessly,", "I'm new can I have food", "I'm not gay, but $20 is $20", "im using ubuntu but i might buy a linux computer", "<insert meme here>", "internet game shithole", "Investigate 3/11", "I only wanted what was best for her...", "I recognize that block,", "I solemnly swear I don't have a life...", "I spent three hours last night trying to get", "is this sever stone made ?", "It does not end.",
        "It is crying.", "It is inevitable.", "It is meaningless.", "It's all connected!", "ITS ALL CONNECTED", "its all connected guays", "its backdoored dont join", "It's called destroy, not grief", "It's downward from here", "It's more of a hell than the nether", "its only a block game", "It's sandcastles man", "It's wabbit season!", "It will all be over soon.", "It will be done my Lord", "I want to die. It's not a joke anymore.", "I will now be looking at the MOTD's", "Jesus approves vetarians", "Jet fuel can't melt iron blocks", "Joining is now disabled due to an exploit.", "join our digital lego club today!", "join r/2b2t!", "Join team vetrain today!", "Journey before Destination",
        "Journey to the world border!", "Just 5 More Minutes...", "Just ask for trees!", "Just don't read chat", "Just pretend it's yogurt", "Kek!", "Kek'd and check'd.", "/kill", "Kill them all... before they kill you...", "lag is good", "least advertised server ever", "Leave now while you still can.", "LEGALIZE RANCH!", "Let go.", "lets play 2b2t!", "Lets Play A Game...", "Like No Other", "Live Free, Die Hard!", "Logging in is temporarily disabled", "Look around... They will all betray you...", "look, he's dead", "looking for moderators apply now!", "Made in North Korea", "Maintain a positive attitude!", "MAKE AMERICA GREAT AGAIN!", "Make Fort Dick Great Again!", "may contain nuts.", "mellons",
        "memes were disabled due to an exploit", "mom its just a entire day wasted", "More than a meme", "more than just a block game", "mountains get big because", "My heart is at The Lands.", "My stepdads play here", "my syndrome may be down,", "Name a wither at spawn", "Nationwide is on your side", "needs more fire", "never forget donkeycaust", "New dupe discovered!", "NEW DUPE, GET ON!", "New map!!!!", "NEW WEBSITE UP VERY SOON!", "nice", "No.", "Nobody is amused", "NO GO AWAY DON'T COME HERE YOU CAN'T L", "No, I won't get out of your shed.", "No! Not Gravy! Nooooooo!", "No Step On Snek", "Not actually the oldest server in Minecraft.", "Notch approved server!", "Nothing ever lasts", "nothing ever lasts, so just give up now",
        "-NO TRANNIES ALLOWED - FP MALES ONLY", "Not your personal daycare.", "Now 100% Faction Free!", "now activating THE WUKON MACHINE", "NOW DO THE HARLEM SHAKE", "Now hiring! Jews in sombreros", "Now with 100% more end!", "Now with circles", "Now with daily doses of crashes!", "Now with kits!", "now with midroll ads!", "Null", "OBEY", "of all the things youv'e lost,", "Oh shit it's going down", "Oh shoot", "ok", "once you go black you never go back", "Once you join YOU CAN'T UNJOIN", "one who sees all", "ONE YEAR", "OOMPALOOMPA.avi", "op is a faggot", "ores before whores", "Or try our diet edition", "Our horses have dicks!", "OwO What's this?", "Pain and misery follow", "peace of shit lag", "peice of a shit lag", "PEPIS BENIS",
        "pepsi > all other", "pepsi > coke", "Pinging...", "Placing blocks is now disabled due to an exploit", "Please stop destroying my spawn", "plos help i am vetrin member", "Pocket edition is better", "Position in queue: 1835", "Position in queue: 940", "Praise be thy melon!", "PRAISE OUR LORD AND SAVIOR, DONKEH", "praise praise praise praise praise", "praise Shrek", "Pretend its 2013 everyday!", "Problems are not stop signs, they are guidelines.", "Proud Sponsor of My Little Pony", "pushin rope, all day, every day", "PVP has been disabled due to an exploit", "Rated R for retardation", "RC Cola > Pepsi", "Real life sucks anyway!", "Real life sucks anyways.", "rebirth", "Red Pill or Blue Pill", "REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
        "remember, no rashen", "Remember to be friendly!", "Remember to tame parrots with cookies!", "Right or wrong, it's very pleasant", "ROBLOX IS BETTER", "Roleplay dupe is best dupe.", "rrerr", "Rules", "sample text", "See! I do care!", "See you @30mil", "Self improvement is masturbation.", "Semper inops quicumque cupit.", "serious pvpers", "Server shutting down in 5 seconds.", "SEVEN YEARS", "shitty graphics", "Shoo-Bee-Doo, Shoo-Shoo Bee-Doo", "Show off your digital girth!", "Shulkerbox in a shulkerbox in a shulkerbox in a...", "SHUT IT DOWN", "silentpedro.mp4", "Singleplayer with cancerous chat.", "Si vis pacem, para bellum.", "SIX YEARS", "Sleep deprivation is a drug.", "smh tbh fam", "So hard to die.", "Something new disabled weekly!",
        "soon a map of north korea", "Sooner or later,", "Sound disabled due to an exploit", "spank me daddy RAWN xD", "sponsored by church taxes", "Sponsored by the Trump Administration.", "stop reading this and start", "SUBMIT! SUBMIT! SUBMIT! SUBMIT! SUBMIT! SUBMIT!", "succ", "S U C C", "SUPERJAIL", "Surprisingly chewey.", "Swearing is a big no no it will result in a ban", "TEAMMENTOS", "Team veterinarian", "Temp map.", "THAT'S THE POWER OF THE KEYBLADE!", "THAW THAW THAW THAW THAW THAW THAW THAW", "The Beginning of The End is HERE!!!", "The best 2b2t clone", "the best minecraft server in the universe", "The darkness spreads.", "the diamond", "The disabling of exploits has been disabled", "THE DUPE IS DEAD!!!", "THE FINAL FRONTIER",
        "The Minecraft equivalent of a Diseny attraction", "The nether is now disabled", "The Oldest Christian Family Friendly Server!!", "There are currently 3 working dupes", "The reason trump won", "There is always a dupe", "There is always a workaround.", "There is no escape...", "THERE IS NO SAFE", "There is still salvation and hope for you", "There's always a dupe!", "There's no right, there's no wrong,", "The shit storm is obvious now", "The world oldest Faction server", "the yacht heist in under 6 minutes", "They told me I could write anything", "They will betray you.", "The Zone will consume you.", ":thinking:", "This again...", "This ends you.", "this is a christian server, do not swear", "This is alien to me.", "This is a sever MOTD message",
        "this is not a fractions server", "this is now dead", "this is why we can't have nice things", "This MOTD requires a 2b2t GOLD account™.", "This place is scary.", "This server is clickbait", "THREE YEARS", "Time to smoke weed and eat pizza", "Time will become your worst enemy,", "TO GET OUT OF SPAWN YOU NEED TO EAT", "Traps are not gay!", "trigonometry has no real world applications", "Trust everyone", "Trust is your weakness...", "Trust me, I'm a doctor.", "Trust no one", "TRUST NO ONE.", "TRUTH ABOUT FIT'S BASE EXPOSED!!", "Twilight Sparkle is best pony.", "two bee two tee dot org", "TWO YEARS", "Type /kill cow for steak!", "Type /kill yes or /kill no to vote!", "TYRONE IS POBBOB!1!1!!1!1!1!!1!1!!!1", "UNDEAD", "unstoppable", "ur mom plays here",
        "Use the 1.12 narrator.", "u w0t m9?", "Walking is temporarily disabled due to an exploit", "WALL", "want to build a base together?", "Want to build a base together?", "We all never belonged here,", "We are an equal opportunity community", "website:", "We found your stash", "Welcome Back", "Welcome, Dave", "WELCOME TO DIE", "welcome to spawn", "Welcome to the oldest server in Minecraft!", "Well, at least we still have maps.", "We need a new dupe.", "We're so far out!", "we will fuck ur mom", "wew lad", "What?", "what are you waiting for?", "What can change the nature of man?", "what command to tp", "what is a 'grief' anyway?", "What is a MOTD?", "what is real anymore", "whats a 2b2?????", "Whats the reason for joining this time?", "Where am I going?",
        "where are the maps?", "where does the ocean end ??", "Where'd you go, psycho boy?", "Where is the mellon highway", "Where's the lamb sauce!?", "Where Tradition Meets Tomorrow", "Which SCP number is 2b2t?", "which side are you, joe", "WHO IS MINING VINES AND OBSIDIAN???", "who is this mysterious and", "whomst'd've broke my maps!", "who's mining obsidian and vines", "who turned out the lights", "why do i feel pain", "why is avacado so expensive?", "wooga", "Worlds Best Cup of Coffee!", "X 145,200 Y 63 Z -803,450", "Yeah I have made a mistake", "YES NO YES NO YES NO YES NO YES NO YES NO", "Yes please", "yiff", "you are banned from this server,", "You are the reason this place is on a watchlist.", "You can never leave. It never ends.", "You can never leave this place.",
        "You can't change spawn.", "You could have stopped it.", "You didn't think that was it did you?", "You die when you are killed.", "you find all types of people,", "You have nowhere else to go!", "You hear my name, you will know who I am.", "you'll be back, you'll always be back", "you never know, it may just make it to the MOTD", "your boat looks terrible,", "You're already dead", "Your inbox has (13) new messages", "You thought it was over,", "You will be alone in the end...", "You won't last long here"
    ];

    let random_motd = motd_vec[rng().random_range(0..=motd_vec.len() - 1)];

    let msg = format!("{}", random_motd);

    msg
}